import BaseLayout from "@/components/BaseLayout";
import {Paper} from "@mui/material";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en" dir="ltr">

      <body>
      <BaseLayout>{children}</BaseLayout>


      </body>

    </html>
  )
}
