"use client"
import '@/styles/globals.css'
import {Inter} from 'next/font/google'
import Head from 'next/head'

import {Container} from '@mui/material';
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const inter = Inter({subsets: ['latin']})
const theme = {
    background: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
};

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const BaseLayout = ({children}) => {
    return (
        <>
            <Head>
                <title>Todos App</title>
                <meta name="description" content="Todos app with Material UI"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>
            <Container sx={{minHeight:'70vh'}}>
                { children }
            </Container>
            <Footer sx={{minHeight:'20vh'}} />
        </>
    )
}
export default BaseLayout;
